name: Go Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - run: mkdir -p dist

    - name: Build and Archive binaries (Windows)
      if: matrix.goos == 'windows'
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }}.exe .
        zip -r dist/yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }}.zip dist/yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }}.exe

    - name: Build and Archive binaries (Linux/macOS)
      if: matrix.goos != 'windows'
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }} .
        tar -czvf dist/yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz -C dist yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/yadisk-uploader-${{ matrix.goos }}-${{ matrix.goarch }}.*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/yadisk-uploader-linux-amd64.tar.gz
          dist/yadisk-uploader-darwin-amd64.tar.gz
          dist/yadisk-uploader-windows-amd64.zip
          dist/yadisk-uploader-linux-arm64.tar.gz
          dist/yadisk-uploader-darwin-arm64.tar.gz
          dist/yadisk-uploader-windows-arm64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
